# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 78dabcb47f3638d823fcca9cb2434810233e7dec

$(eval $(call build_engine,jint,Dockerfile))
