# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 71357f1638bc36831a0ef5aa37c3cca7bbd6c145

$(eval $(call build_engine,jint,Dockerfile))
