# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

CONFORMANCE_SUITE = es[1-5]
SUPPORTED_ARCHS = amd64

$(eval $(call build_engine,malbrain,Dockerfile))
