# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 461716f4f380f81ffd09378751f1812919cddbca

$(eval $(call build_engine,fastschema-qjs,Dockerfile))
