# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 66fca446da4e3669db0ae67448ef7cc7ea8f307c

$(eval $(call build_engine,nova,Dockerfile))
