# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= d441adbc01ddc7e3b296780a64a4c3b3eff9b1d7

$(eval $(call build_engine,nova,Dockerfile))
