# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

# arm64 build is broken
SUPPORTED_ARCHS = amd64

$(eval $(call build_engine,starlight,Dockerfile))
