# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 821447737f3d2f79139cef97be16f4513dd75099

$(eval $(call build_engine,tiny-js,Dockerfile))
