# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= b198c6df7edc2b88afef998a2147ab76f2802fae

$(eval $(call build_engine,yavashark,Dockerfile))
