# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 9e45eb4e74e5ae0cd88e65fd2dcc95fff77c8c7d

$(eval $(call build_engine,yavashark,Dockerfile))
