# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 826fe4eba8273447e9b1f88c92293a2cd407585f

$(eval $(call build_engine,syoyo,Dockerfile))
