# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 8bbf01215ce30971eb02eee2250d51e422f700e6

$(eval $(call build_engine,ucode,Dockerfile))
