# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

# https://dart.dev/get-dart architectures
SUPPORTED_ARCHS = amd64 arm64 riscv64

$(eval $(call build_engine,kodjodevf,Dockerfile))
