# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

# LuaJIT platforms
SUPPORTED_ARCHS = amd64 arm64 arm 386 riscv64 s390x

$(eval $(call build_engine,castl,Dockerfile))
