# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 7d6f6c5713493e9fe737fb1435c11f690497fe4c

$(eval $(call build_engine,castl,Dockerfile))
