# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 5b8985372d34dc3327c20dcbfc9a4b85d948c52b

$(eval $(call build_engine,sandboxjs,Dockerfile))
