# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 2e55cdd94f0289cb7726647193e5212ab13d39b4

$(eval $(call build_engine,quanta,Dockerfile))
