# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 04bcf711ebf69bdcc31a4ae6b66411af471b7a7a
SUPPORTED_ARCHS = amd64 arm64

$(eval $(call build_engine,quanta,Dockerfile))
