# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= f1ba573b23262e45822f3159f7324c661b839e1a

$(eval $(call build_engine,quanta,Dockerfile))
