# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= afb4a5d188a2461aee959891eab7f958279b1115

$(eval $(call build_engine,yantra,Dockerfile))
