# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 86373defd8d1a8980cb95055359231e1b2a45782

$(eval $(call build_engine,engine262,Dockerfile))
