# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 4d5d1d017bb82a002adb06f997d7e0d57bb71226

$(eval $(call build_engine,engine262,Dockerfile))
