# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= graal-25.0.2
SUPPORTED_ARCHS = amd64 arm64

$(eval $(call build_engine,graaljs,Dockerfile))
