# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= cb47fa5b1e924e029e5b490cd22f99b6f58b7f72

$(eval $(call build_engine,boa,Dockerfile))
