# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= ab52d7abffc60bc218bcb5891637efeff7119274

$(eval $(call build_engine,boa,Dockerfile))
