# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 1c271815cf13291d3e4b636999ff7ecd7aa0993b

$(eval $(call build_engine,besen,Dockerfile))
