# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= ee50431eac9b14b99f722b537ec4cac0c8dd75ab

$(eval $(call build_engine,mquickjs,Dockerfile))
