# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 09a97d72d5c62223fc11bdee75565f3e9b39af46

$(eval $(call build_engine,criscript,Dockerfile))
