# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

CONFORMANCE_SUITE = es[1-5]

REV ?= RELEASE_2V28

$(eval $(call build_engine,espruino,Dockerfile))
