# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 455b1eb10f919ef9f26533a8b741d61e2b3e98c9

$(eval $(call build_engine,stator,Dockerfile))
