# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 3ca729876b8973d2faeb6f25d1c8e7dd6580063a

$(eval $(call build_engine,otto,Dockerfile))
