# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

# Non-portable 32-bit x86 code
SUPPORTED_ARCHS = amd64 386

$(eval $(call build_engine,dscriptcpp,Dockerfile))
