# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

SUPPORTED_ARCHS = amd64
REV ?= 291637d5a34087fd7237ec0a2bf91daaac17e4d5

$(eval $(call build_engine,ant,Dockerfile))
