# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= a41eb672dfe434f78be3ba1443774daa973eb2e1

$(eval $(call build_engine,ant,Dockerfile))
