# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

# Build platforms for WASI SDK
SUPPORTED_ARCHS = amd64 arm64

$(eval $(call build_engine,starlingmonkey,Dockerfile))
