# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 637e0ba1f3314c5658e4dd3da429102739ea7eae

$(eval $(call build_engine,kiesel,Dockerfile))
