# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 4f059b5a0e1cd4a5434123a75d927f547b5a9a85

$(eval $(call build_engine,kiesel,Dockerfile))
