# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 11f084fc09723785b4bdb0575509664ca8b05f49

$(eval $(call build_engine,delskayn,Dockerfile))
