# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 943e5c09470813e26404bd3920b93601fcc5b46b

$(eval $(call build_engine,zhuzilin,Dockerfile))
