# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= bdae4a158e94eee2e6ea388640499d41ff40ee13

$(eval $(call build_engine,sobek,Dockerfile))
