# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= f23f5510d87e6e8466263cbe36386e556d24f516

$(eval $(call build_engine,sobek,Dockerfile))
