# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

SUPPORTED_ARCHS = amd64 arm64 386 ppc64le s390x

$(eval $(call build_engine,rapidus,Dockerfile))
