# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= e2cbce0e2ee7bb640df056d790e7d5e61fde94e0

$(eval $(call build_engine,rapidus,Dockerfile))
