# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 3d109cbf6d185c3665da2982e92ce198406cca01

$(eval $(call build_engine,mocha,Dockerfile))
