# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

# Platforms of prebuilt binaries
SUPPORTED_ARCHS = amd64 arm64

$(eval $(call build_engine,sablejs,Dockerfile))
