# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= f93cb97b5ec1c665648f369b0fb96ff82155cdfb

$(eval $(call build_engine,dmdscript,Dockerfile))
