# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= ea022c628175c5488c3186786972b0b7c8b2193e

$(eval $(call build_engine,espresso,Dockerfile))
