# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 6a04fef645608b7995fa119b445e3f18e2281473

$(eval $(call build_engine,brimstone,Dockerfile))
