# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 55e5fa395bad5c1dbf6c44b0fbc26439a40f5773

$(eval $(call build_engine,cesanta-mjs,Dockerfile))
