# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 0ba9a5494a59554ce0c607f80b8a6dec8e9703b3

$(eval $(call build_engine,goja,Dockerfile))
