# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= 2bb4c724c0f93e868b4ab96009bdccb6947a9379

$(eval $(call build_engine,goja,Dockerfile))
