# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= cd10218477ad2ae74436f6c6e5a1bd4995a842c2

$(eval $(call build_engine,porffor,Dockerfile))
