# SPDX-FileCopyrightText: 2026 Ivan Krasilnikov
# SPDX-License-Identifier: MIT

include ../../build/build.mk

REV ?= d8b91bad05c56954cd2bcffd164e3d64bc4fcab0

$(eval $(call build_engine,porffor,Dockerfile))
